<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="css/splide.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap" rel="stylesheet">
</head>
<body>
  <?php include("header.php");?>
  <main>
    <div class="container">
      <div class="row">
        <div class="col-2-5-10 mg-l-0">
          &nbsp;
        </div>
        <div class="col-5-10 mg-l-0">
          <table id="cart">
            <thead>
              <tr>
                <th>id</th>
                <th>color</th>
                <th>size</th>
                <th>quantity</th>
                <th>unit price</th>
                <th>total</th>
              </tr>
            </thead>
          </table>
            <a id="db" href="#" class="checkout-button">Next</a> <input type="radio" name="LP" value="Local payment"> Pay when arrived
        </div>
        <div class="col-2-5-10 mg-l-0">
          &nbsp;
        </div>
      </div>
    </div>
  </main>

  <?php include("footer.php");?>


  <script src="js/main.js" charset="utf-8"></script>
    <script src="js/jquery-3.5.1.min.js" charset="utf-8"></script>
  <script type="text/javascript">
  var cartProducts = localStorage.getItem("cart");
  if (cartProducts == null)
  {
    //Show a message and say your cart is empty
  }
  else{
    const table = document.getElementById("cart");
    while (cartProducts.length>0){//unti the cart is not empty repeat this loop
      let s = cartProducts.indexOf('[');
      let e = cartProducts.indexOf(']');
      let product = cartProducts.substring(s,e+1);
      var list = JSON.parse(product);
      let row = table.insertRow();
      for(var i=0;i<list.length;i++)
      {
        let cell = row.insertCell(i);
        cell.innerHTML = list[i];
      }
      let cell = row.insertCell(i);
      cell.innerHTML = "sum";
      cartProducts = cartProducts.replace(product,'');
    }
  }
</script>
<?php if($_GET['login']=='fail'){
  echo '<script type="text/javascript">modal();</script>';
}?>
<script>
$('#db').click(function(){
  var checkoutProducts = localStorage.getItem("cart");
  if (cartProducts == null)
  {
    //Show a message and say your cart is empty
  }
  else{

    while (checkoutProducts.length>0){//unti the cart is not empty repeat this loop
      let s = checkoutProducts.indexOf('[');
      let e = checkoutProducts.indexOf(']');
      let cart = checkoutProducts.substring(s,e+1);
      var list = JSON.parse(cart);
      var action = 'fetch_data';
      var productId = list[0];
      var colorId = list[1];
      var productSize = list[2];
      var orderAmount = list[3];
      checkoutProducts = checkoutProducts.replace(cart,'');
      $.ajax({
        type: "POST",
        url:"checkout.php",
        data:{
          'action':action,
          'productId':productId,
          'colorId':colorId,
          'productSize':productSize,
          'orderAmount':orderAmount
        }
      })
      .done(function(data){
        console.log("success");
      })
      .fail(function(){
        console.log("fail");
        alert("error");
      })
    }
    window.localStorage.clear();
    sessionStorage.removeItem("cart-products");
    window.location.href= "thanks.php";
  }


});


</script>
</body>
</html>
