<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="css/splide.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap" rel="stylesheet">
</head>
<body>
<?php include("header.php");?>



<div class="container">

<div class="row">
  <div class="col-2-5-10">
<p>&nbsp;</p>
  </div>
<div class="col-5-10">

<h2>Registration Form</h2>
Plese complete the following form to register in our website.

    <form id="registeration-form" action="register.php" method="post">
      <p>
    <label for="fname">First Name</label>
    <input type="text" id="fname" name="fname" placeholder="Your name..." required>

</p>
<p>
    <label for="lname">Last Name</label>
    <input type="text" id="lname" name="lname" placeholder="Your last name.." required>

</p>

<p>
    <label for="email">Email</label>
    <input type="text" id="email" name="email" placeholder="Example: tina@gamil.com" required>

</p>
<p>
    <label for="phone">Phone Number</label>
    <input type="text" id="phone" name="phone" placeholder="Your phone number" required>

</p>
<p>
    <label for="address">Postal Address</label>
    <input type="text" id="address" name="address" placeholder="Your complete postal address" required>

</p>
<p>
  <label for="psw">Password</label>
  <input type="password" id="psw" name="psw" placeholder="Your password" required>

</p>
<p>
  <label for="psw">Repeat password</label>
  <input type="password" id="reppsw" name="reppsw" placeholder="Type your password again" required>

</p>
    <input type="submit" value="Submit">
  </form>
  </div>
  <div class="col-2-5-10">
<p>&nbsp;</p>
  </div>
</div>
</div>

<?php include("footer.php");?>
<script src="js/main.js" charset="utf-8"></script>
</body>

</html>
