<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="css/splide.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap" rel="stylesheet">
</head>
<body>
<?php include("header.php");?>



<div class="container">
<div class="row">
<p>Thank you for your shop, you can see the status of your order in your <a href="profile.php">profile</a></p>
</div>
</div>

<?php include("footer.php");?>
<script src="js/main.js" charset="utf-8"></script>
</body>

</html>
